POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer xxxxx

{
    "title": "Skateboarding",
    "author": "Mazuel",
    "url": "www.google.com",
    "likes": 14
}
###

GET http://localhost:3003/api/blogs

###

DELETE http://localhost:3003/api/blogs/61915bfa94779814ac026450
Authorization: Bearer xxxxx
###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "Mazuel",
    "password": "test123" 
}

####

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "KOrra",
    "password": "helloyoutube",
    "name": "Maz Kaz"
}

####

GET http://localhost:3003/api/users